[tasks.srchash]
run = """
find src -type f -name '*.k' -print0 | sort -z | xargs -0 cat | sha1sum | awk '{print $1}'
"""

[tasks.build]
sources = ['src/**/*']
run = """
mkdir -p build
NEW_HASH=$(mise run srchash --quiet)

if [ -f build/src_hash ]; then
  OLD_HASH=$(cat build/src_hash)
else
  OLD_HASH=""
fi

if [ -f build/last_build_succeed ]; then
  LAST_BUILD_SUCCEED=$(cat build/last_build_succeed)
else
  LAST_BUILD_SUCCEED=false
fi

if [ "$NEW_HASH" = "$OLD_HASH" ] && [ "$LAST_BUILD_SUCCEED" = "true" ]; then
  echo 'Source hash unchanged, skipping build.'
  echo false > build/has_new_build
  exit 0
else
  echo "$NEW_HASH" > build/src_hash
  echo 'Rebuilding...'
  if kompile src/ts-main.k --output-definition compiled --gen-glr-bison-parser; then
    echo 'Kompile successful'
    echo true > build/has_new_build
    echo true > build/last_build_succeed
  else
    echo 'Kompile failed'
    echo false > build/last_build_succeed
    exit 1
  fi
fi
"""
